"""added subcustomerprobeevent table

Revision ID: 0a639f33bdf1
Revises: 29c2d9db934d
Create Date: 2026-07-14 17:02:26.391881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0a639f33bdf1'
down_revision: Union[str, None] = '29c2d9db934d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcustomerprobeevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_customer_id', sa.Integer(), nullable=False),
    sa.Column('application_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_found', sa.Boolean(), nullable=False),
    sa.Column('account_deleted', sa.Boolean(), nullable=False),
    sa.Column('account_active', sa.Boolean(), nullable=False),
    sa.Column('grace_period_active', sa.Boolean(), nullable=False),
    sa.Column('service_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcustomerprobeevent_application_tag'), 'subcustomerprobeevent', ['application_tag'], unique=False)
    op.create_index(op.f('ix_subcustomerprobeevent_primary_customer_id'), 'subcustomerprobeevent', ['primary_customer_id'], unique=False)
    op.create_index(op.f('ix_subcustomerprobeevent_sub_customer_email'), 'subcustomerprobeevent', ['sub_customer_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcustomerprobeevent_sub_customer_email'), table_name='subcustomerprobeevent')
    op.drop_index(op.f('ix_subcustomerprobeevent_primary_customer_id'), table_name='subcustomerprobeevent')
    op.drop_index(op.f('ix_subcustomerprobeevent_application_tag'), table_name='subcustomerprobeevent')
    op.drop_table('subcustomerprobeevent')
    # ### end Alembic commands ###
