"""sandbox count and livemode related updates

Revision ID: 13bfd4b363b7
Revises: 3dff112a0c84
Create Date: 2026-07-16 20:44:46.138826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13bfd4b363b7'
down_revision: Union[str, None] = '3dff112a0c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('sandbox_count', sa.Integer(), nullable=True))
    op.add_column('stripeevent', sa.Column('sandbox_hook', sa.Boolean(), nullable=True))
    op.add_column('stripeevent', sa.Column('sandbox_mismatch', sa.Boolean(), nullable=True))
    op.add_column('subcustomer', sa.Column('sandbox_count', sa.Integer(), nullable=True))
    op.add_column('subcustomerprobeevent', sa.Column('sandbox_count', sa.Integer(), nullable=True))
    op.add_column('subscribertransaction', sa.Column('sandbox_mismatch', sa.Boolean(), nullable=True))
    op.add_column('subsubscribertransaction', sa.Column('sandbox_mismatch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsubscribertransaction', 'sandbox_mismatch')
    op.drop_column('subscribertransaction', 'sandbox_mismatch')
    op.drop_column('subcustomerprobeevent', 'sandbox_count')
    op.drop_column('subcustomer', 'sandbox_count')
    op.drop_column('stripeevent', 'sandbox_mismatch')
    op.drop_column('stripeevent', 'sandbox_hook')
    op.drop_column('customer', 'sandbox_count')
    # ### end Alembic commands ###
