"""add_share_link_tables_and_enums

Revision ID: 1fa893e89191
Revises: a998d73dda92
Create Date: 2026-08-05 21:51:45.468842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fa893e89191'
down_revision: Union[str, None] = 'a998d73dda92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('open_access', 'email_any_unverified', 'email_any_verified', 'email_matching', 'email_matching_verified', 'recipient_email_verified', 'password_only', 'password_with_email_any_unverified', 'password_with_email_any_verified', 'password_with_email_matching', 'password_with_email_matching_verified', 'password_with_recipient_email_verified', 'not_specified', name='shareaccesscheckmode').create(op.get_bind())
    sa.Enum('not_set', 'vote', 'vote_view', 'report', name='sharetype').create(op.get_bind())
    op.create_table('sharelink',
    sa.Column('shared_type', postgresql.ENUM('not_set', 'vote', 'vote_view', 'report', name='sharetype', create_type=False), nullable=False),
    sa.Column('shared_entity_db_id', sa.Integer(), nullable=False),
    sa.Column('link_auto_send', sa.Boolean(), nullable=False),
    sa.Column('shared_with_company_name', sa.String(), nullable=True),
    sa.Column('shared_with_person_name', sa.String(), nullable=True),
    sa.Column('shared_with_email', sa.String(), nullable=True),
    sa.Column('share_link_name', sa.String(), nullable=True),
    sa.Column('share_link_expiration', sa.Integer(), nullable=False),
    sa.Column('access_mode', postgresql.ENUM('open_access', 'email_any_unverified', 'email_any_verified', 'email_matching', 'email_matching_verified', 'recipient_email_verified', 'password_only', 'password_with_email_any_unverified', 'password_with_email_any_verified', 'password_with_email_matching', 'password_with_email_matching_verified', 'password_with_recipient_email_verified', 'not_specified', name='shareaccesscheckmode', create_type=False), nullable=False),
    sa.Column('share_password', sa.String(), nullable=True),
    sa.Column('share_password_in_email', sa.Boolean(), nullable=False),
    sa.Column('cookie_duration', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magic_token', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('share_link_enabled', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharelink_customer_id'), 'sharelink', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sharelink_magic_token'), 'sharelink', ['magic_token'], unique=True)
    op.create_index(op.f('ix_sharelink_shared_entity_db_id'), 'sharelink', ['shared_entity_db_id'], unique=False)
    op.create_table('sharelinkaccessed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('share_magic_token', sa.String(), nullable=True),
    sa.Column('cookie_token', sa.String(), nullable=False),
    sa.Column('shared_entity_db_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('remote_ip', sa.String(), nullable=True),
    sa.Column('url_path', sa.String(), nullable=True),
    sa.Column('access_operation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_customer_id', sa.Integer(), nullable=True),
    sa.Column('captured_email', sa.String(), nullable=True),
    sa.Column('captured_display_name', sa.String(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharelinkaccessed_cookie_token'), 'sharelinkaccessed', ['cookie_token'], unique=False)
    op.create_index(op.f('ix_sharelinkaccessed_customer_id'), 'sharelinkaccessed', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sharelinkaccessed_share_id'), 'sharelinkaccessed', ['share_id'], unique=False)
    op.create_index(op.f('ix_sharelinkaccessed_shared_entity_db_id'), 'sharelinkaccessed', ['shared_entity_db_id'], unique=False)
    op.create_table('sharelinkmagickey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('share_magic_token', sa.String(), nullable=True),
    sa.Column('access_magic_key', sa.String(), nullable=True),
    sa.Column('share_token_and_access_magic_key', sa.String(), nullable=True),
    sa.Column('captured_email', sa.String(), nullable=True),
    sa.Column('captured_display_name', sa.String(), nullable=True),
    sa.Column('original_link_recipient_email', sa.String(), nullable=True),
    sa.Column('accessed_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharelinkmagickey_share_id'), 'sharelinkmagickey', ['share_id'], unique=False)
    op.create_index(op.f('ix_sharelinkmagickey_share_token_and_access_magic_key'), 'sharelinkmagickey', ['share_token_and_access_magic_key'], unique=True)
    op.add_column('customerproject', sa.Column('magic_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_customerproject_magic_token'), 'customerproject', ['magic_token'], unique=True)
    op.alter_column('user', 'client_settings',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='CASE WHEN client_settings IS NULL OR client_settings = \'\' THEN NULL ELSE client_settings::jsonb END',
               existing_nullable=True)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='outboundemailtype',
        new_values=['password_reset', 'customer_activation_self', 'customer_activation_admin', 'customer_activation_admin_activated', 'new_user_welcome', 'share_project_vote', 'share_project_vote_view', 'share_project_report', 'magic_access_key', 'not_set'],
        affected_columns=[TableReference(table_schema='public', table_name='emailactivitylog', column_name='email_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='outboundemailtype',
        new_values=['password_reset', 'customer_activation_self', 'customer_activation_admin', 'customer_activation_admin_activated', 'new_user_welcome', 'share_profile_view', 'share_profile_edit', 'invite_founder', 'magic_access_key', 'not_set'],
        affected_columns=[TableReference(table_schema='public', table_name='emailactivitylog', column_name='email_type')],
        enum_values_to_rename=[],
    )
    op.alter_column('user', 'client_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               postgresql_using='client_settings::text',
               existing_nullable=True)
    op.drop_index(op.f('ix_customerproject_magic_token'), table_name='customerproject')
    op.drop_column('customerproject', 'magic_token')
    op.drop_index(op.f('ix_sharelinkmagickey_share_token_and_access_magic_key'), table_name='sharelinkmagickey')
    op.drop_index(op.f('ix_sharelinkmagickey_share_id'), table_name='sharelinkmagickey')
    op.drop_table('sharelinkmagickey')
    op.drop_index(op.f('ix_sharelinkaccessed_shared_entity_db_id'), table_name='sharelinkaccessed')
    op.drop_index(op.f('ix_sharelinkaccessed_share_id'), table_name='sharelinkaccessed')
    op.drop_index(op.f('ix_sharelinkaccessed_customer_id'), table_name='sharelinkaccessed')
    op.drop_index(op.f('ix_sharelinkaccessed_cookie_token'), table_name='sharelinkaccessed')
    op.drop_table('sharelinkaccessed')
    op.drop_index(op.f('ix_sharelink_shared_entity_db_id'), table_name='sharelink')
    op.drop_index(op.f('ix_sharelink_magic_token'), table_name='sharelink')
    op.drop_index(op.f('ix_sharelink_customer_id'), table_name='sharelink')
    op.drop_table('sharelink')
    sa.Enum('not_set', 'vote', 'vote_view', 'report', name='sharetype').drop(op.get_bind())
    sa.Enum('open_access', 'email_any_unverified', 'email_any_verified', 'email_matching', 'email_matching_verified', 'recipient_email_verified', 'password_only', 'password_with_email_any_unverified', 'password_with_email_any_verified', 'password_with_email_matching', 'password_with_email_matching_verified', 'password_with_recipient_email_verified', 'not_specified', name='shareaccesscheckmode').drop(op.get_bind())
    # ### end Alembic commands ###
