"""add watcher queues

Revision ID: 20ba6b8d0df6
Revises: x5y6z7a8b9c0
Create Date: 2026-08-24 01:44:21.689699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20ba6b8d0df6'
down_revision: Union[str, None] = 'x5y6z7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - trimmed to watcher queues only ###
    op.create_table('watcher_api_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('http_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_params_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watcher_api_requests_auth_protocol'), 'watcher_api_requests', ['auth_protocol'], unique=False)
    op.create_index('ix_watcher_api_requests_claim', 'watcher_api_requests', ['status', 'next_attempt_at', 'id'], unique=False)
    op.create_index(op.f('ix_watcher_api_requests_connection_protocol'), 'watcher_api_requests', ['connection_protocol'], unique=False)
    op.create_index(op.f('ix_watcher_api_requests_created_by_user_id'), 'watcher_api_requests', ['created_by_user_id'], unique=False)
    op.create_index('ix_watcher_api_requests_customer', 'watcher_api_requests', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_watcher_api_requests_customer_id'), 'watcher_api_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_watcher_api_requests_next_attempt_at'), 'watcher_api_requests', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_watcher_api_requests_semantic_tag'), 'watcher_api_requests', ['semantic_tag'], unique=False)
    op.create_index(op.f('ix_watcher_api_requests_status'), 'watcher_api_requests', ['status'], unique=False)
    op.create_table('watcher_email_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watcher_email_requests_claim', 'watcher_email_requests', ['status', 'next_attempt_at', 'id'], unique=False)
    op.create_index(op.f('ix_watcher_email_requests_created_by_user_id'), 'watcher_email_requests', ['created_by_user_id'], unique=False)
    op.create_index('ix_watcher_email_requests_customer', 'watcher_email_requests', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_watcher_email_requests_customer_id'), 'watcher_email_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_watcher_email_requests_next_attempt_at'), 'watcher_email_requests', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_watcher_email_requests_semantic_tag'), 'watcher_email_requests', ['semantic_tag'], unique=False)
    op.create_index(op.f('ix_watcher_email_requests_status'), 'watcher_email_requests', ['status'], unique=False)
    op.create_index(op.f('ix_watcher_email_requests_to_email'), 'watcher_email_requests', ['to_email'], unique=False)
    op.create_table('watcher_generic_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watcher_generic_jobs_claim', 'watcher_generic_jobs', ['status', 'next_attempt_at', 'id'], unique=False)
    op.create_index(op.f('ix_watcher_generic_jobs_created_by_user_id'), 'watcher_generic_jobs', ['created_by_user_id'], unique=False)
    op.create_index('ix_watcher_generic_jobs_customer', 'watcher_generic_jobs', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_watcher_generic_jobs_customer_id'), 'watcher_generic_jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_watcher_generic_jobs_next_attempt_at'), 'watcher_generic_jobs', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_watcher_generic_jobs_semantic_tag'), 'watcher_generic_jobs', ['semantic_tag'], unique=False)
    op.create_index(op.f('ix_watcher_generic_jobs_status'), 'watcher_generic_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_watcher_generic_jobs_work_type'), 'watcher_generic_jobs', ['work_type'], unique=False)
    op.create_table('watcher_llm_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('messages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watcher_llm_requests_claim', 'watcher_llm_requests', ['status', 'next_attempt_at', 'id'], unique=False)
    op.create_index(op.f('ix_watcher_llm_requests_created_by_user_id'), 'watcher_llm_requests', ['created_by_user_id'], unique=False)
    op.create_index('ix_watcher_llm_requests_customer', 'watcher_llm_requests', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_watcher_llm_requests_customer_id'), 'watcher_llm_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_watcher_llm_requests_next_attempt_at'), 'watcher_llm_requests', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_watcher_llm_requests_semantic_tag'), 'watcher_llm_requests', ['semantic_tag'], unique=False)
    op.create_index(op.f('ix_watcher_llm_requests_status'), 'watcher_llm_requests', ['status'], unique=False)
    # (trimmed unrelated autogeneration)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (trimmed unrelated autogeneration)
    op.drop_index(op.f('ix_watcher_llm_requests_status'), table_name='watcher_llm_requests')
    op.drop_index(op.f('ix_watcher_llm_requests_semantic_tag'), table_name='watcher_llm_requests')
    op.drop_index(op.f('ix_watcher_llm_requests_next_attempt_at'), table_name='watcher_llm_requests')
    op.drop_index(op.f('ix_watcher_llm_requests_customer_id'), table_name='watcher_llm_requests')
    op.drop_index('ix_watcher_llm_requests_customer', table_name='watcher_llm_requests')
    op.drop_index(op.f('ix_watcher_llm_requests_created_by_user_id'), table_name='watcher_llm_requests')
    op.drop_index('ix_watcher_llm_requests_claim', table_name='watcher_llm_requests')
    op.drop_table('watcher_llm_requests')
    op.drop_index(op.f('ix_watcher_generic_jobs_work_type'), table_name='watcher_generic_jobs')
    op.drop_index(op.f('ix_watcher_generic_jobs_status'), table_name='watcher_generic_jobs')
    op.drop_index(op.f('ix_watcher_generic_jobs_semantic_tag'), table_name='watcher_generic_jobs')
    op.drop_index(op.f('ix_watcher_generic_jobs_next_attempt_at'), table_name='watcher_generic_jobs')
    op.drop_index(op.f('ix_watcher_generic_jobs_customer_id'), table_name='watcher_generic_jobs')
    op.drop_index('ix_watcher_generic_jobs_customer', table_name='watcher_generic_jobs')
    op.drop_index(op.f('ix_watcher_generic_jobs_created_by_user_id'), table_name='watcher_generic_jobs')
    op.drop_index('ix_watcher_generic_jobs_claim', table_name='watcher_generic_jobs')
    op.drop_table('watcher_generic_jobs')
    op.drop_index(op.f('ix_watcher_email_requests_to_email'), table_name='watcher_email_requests')
    op.drop_index(op.f('ix_watcher_email_requests_status'), table_name='watcher_email_requests')
    op.drop_index(op.f('ix_watcher_email_requests_semantic_tag'), table_name='watcher_email_requests')
    op.drop_index(op.f('ix_watcher_email_requests_next_attempt_at'), table_name='watcher_email_requests')
    op.drop_index(op.f('ix_watcher_email_requests_customer_id'), table_name='watcher_email_requests')
    op.drop_index('ix_watcher_email_requests_customer', table_name='watcher_email_requests')
    op.drop_index(op.f('ix_watcher_email_requests_created_by_user_id'), table_name='watcher_email_requests')
    op.drop_index('ix_watcher_email_requests_claim', table_name='watcher_email_requests')
    op.drop_table('watcher_email_requests')
    op.drop_index(op.f('ix_watcher_api_requests_status'), table_name='watcher_api_requests')
    op.drop_index(op.f('ix_watcher_api_requests_semantic_tag'), table_name='watcher_api_requests')
    op.drop_index(op.f('ix_watcher_api_requests_next_attempt_at'), table_name='watcher_api_requests')
    op.drop_index(op.f('ix_watcher_api_requests_customer_id'), table_name='watcher_api_requests')
    op.drop_index('ix_watcher_api_requests_customer', table_name='watcher_api_requests')
    op.drop_index(op.f('ix_watcher_api_requests_created_by_user_id'), table_name='watcher_api_requests')
    op.drop_index(op.f('ix_watcher_api_requests_connection_protocol'), table_name='watcher_api_requests')
    op.drop_index('ix_watcher_api_requests_claim', table_name='watcher_api_requests')
    op.drop_index(op.f('ix_watcher_api_requests_auth_protocol'), table_name='watcher_api_requests')
    op.drop_table('watcher_api_requests')
    # ### end Alembic commands ###
