"""initial

Revision ID: 214c4d6a4a26
Revises: 
Create Date: 2026-07-12 18:25:47.165257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '214c4d6a4a26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiaccessconfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authentication_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shared_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('application_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enable_probe', sa.Boolean(), nullable=False),
    sa.Column('enable_dashboard', sa.Boolean(), nullable=False),
    sa.Column('webhook_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiaccessconfiguration_application_tag'), 'apiaccessconfiguration', ['application_tag'], unique=False)
    op.create_index(op.f('ix_apiaccessconfiguration_authentication_key_id'), 'apiaccessconfiguration', ['authentication_key_id'], unique=True)
    op.create_index(op.f('ix_apiaccessconfiguration_customer_id'), 'apiaccessconfiguration', ['customer_id'], unique=False)
    op.create_table('apiwebinvocationevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('api_configuration_id', sa.Integer(), nullable=True),
    sa.Column('authentication_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unique_tracking_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requesting_transaction_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('web_hook_type', sa.Enum('dummy_value', name='webhooktype'), nullable=True),
    sa.Column('probe_result', sa.Boolean(), nullable=True),
    sa.Column('web_hook_status', sa.Enum('not_applicable', 'waiting', 'pending', 'trying', 'delivered', 'failed', name='webhookstatus'), nullable=True),
    sa.Column('web_hook_delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('web_hook_failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_delivery_attempt_time', sa.DateTime(), nullable=True),
    sa.Column('module_count_requested', sa.Integer(), nullable=False),
    sa.Column('module_count_completed', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiwebinvocationevent_api_configuration_id'), 'apiwebinvocationevent', ['api_configuration_id'], unique=False)
    op.create_index(op.f('ix_apiwebinvocationevent_authentication_key_id'), 'apiwebinvocationevent', ['authentication_key_id'], unique=False)
    op.create_index(op.f('ix_apiwebinvocationevent_customer_id'), 'apiwebinvocationevent', ['customer_id'], unique=False)
    op.create_index(op.f('ix_apiwebinvocationevent_unique_tracking_id'), 'apiwebinvocationevent', ['unique_tracking_id'], unique=True)
    op.create_table('applicationlogevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('computer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('authenticated_session', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_config_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_admin', sa.Boolean(), nullable=False),
    sa.Column('remote_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exception_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exception_trace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kw_details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details_str', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_status', sa.Enum('inactive', 'active', name='accountstatus'), nullable=False),
    sa.Column('customer_activated', sa.Boolean(), nullable=False),
    sa.Column('grace_period_hours', sa.Integer(), nullable=False),
    sa.Column('stripe_settings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_settings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_activation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('service_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_customer_account'), 'customer', ['customer_account'], unique=True)
    op.create_index(op.f('ix_customer_customer_email'), 'customer', ['customer_email'], unique=True)
    op.create_table('customerapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('application_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_stripe_hook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_stripe_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('application_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customerapplication_application_tag'), 'customerapplication', ['application_tag'], unique=False)
    op.create_index(op.f('ix_customerapplication_customer_id'), 'customerapplication', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customerapplication_customer_stripe_hook'), 'customerapplication', ['customer_stripe_hook'], unique=True)
    op.create_table('emailactivitylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_type', sa.Enum('password_reset', 'customer_activation_self', 'customer_activation_admin', 'customer_activation_admin_activated', 'new_user_welcome', 'share_profile_view', 'share_profile_edit', 'invite_founder', 'magic_access_key', 'not_set', name='outboundemailtype'), nullable=False),
    sa.Column('email_params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('remote_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailactivitylog_email_address'), 'emailactivitylog', ['email_address'], unique=False)
    op.create_index(op.f('ix_emailactivitylog_remote_ip'), 'emailactivitylog', ['remote_ip'], unique=False)
    op.create_table('stripeevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_customer_id', sa.Integer(), nullable=True),
    sa.Column('application_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_livemode', sa.Boolean(), nullable=True),
    sa.Column('stripe_nested_object_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_informational_capture_only', sa.Boolean(), nullable=False),
    sa.Column('stripe_invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_checkout_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_lookup_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_product', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_payment_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_charge_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_charge_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_invoice_pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_receipt_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_cancellation_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_transaction_amount', sa.Float(), nullable=False),
    sa.Column('stripe_discount_amount', sa.Float(), nullable=False),
    sa.Column('stripe_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_units', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_add_months_count', sa.Integer(), nullable=False),
    sa.Column('transaction_add_days_count', sa.Integer(), nullable=False),
    sa.Column('transaction_trial_days_count', sa.Integer(), nullable=False),
    sa.Column('latest_transaction_id', sa.Integer(), nullable=False),
    sa.Column('related_log_id', sa.Integer(), nullable=False),
    sa.Column('exception_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exception_severity', sa.Integer(), nullable=False),
    sa.Column('stripe_event_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripeevent_primary_customer_id'), 'stripeevent', ['primary_customer_id'], unique=False)
    op.create_index(op.f('ix_stripeevent_stripe_customer_id'), 'stripeevent', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_stripeevent_stripe_event_id'), 'stripeevent', ['stripe_event_id'], unique=True)
    op.create_table('subcustomer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_customer_id', sa.Integer(), nullable=False),
    sa.Column('application_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_customer_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_activation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('service_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcustomer_application_tag'), 'subcustomer', ['application_tag'], unique=False)
    op.create_index(op.f('ix_subcustomer_primary_customer_id'), 'subcustomer', ['primary_customer_id'], unique=False)
    op.create_index(op.f('ix_subcustomer_sub_customer_account'), 'subcustomer', ['sub_customer_account'], unique=True)
    op.create_index(op.f('ix_subcustomer_sub_customer_email'), 'subcustomer', ['sub_customer_email'], unique=False)
    op.create_table('subscribertransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('financial_transaction_amount', sa.Float(), nullable=False),
    sa.Column('financial_transaction_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('financial_discount_amount', sa.Float(), nullable=False),
    sa.Column('csr_user_id', sa.Integer(), nullable=True),
    sa.Column('csr_user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('csr_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_livemode', sa.Boolean(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'promotion', 'credit', 'usage', 'cancelled', 'note', 'balance_forward', name='subscribertransactiontype'), nullable=False),
    sa.Column('transaction_units', sa.Enum('days', 'months', 'years', name='subscribertransactionunits'), nullable=False),
    sa.Column('transaction_month_count', sa.Integer(), nullable=False),
    sa.Column('transaction_day_count', sa.Integer(), nullable=False),
    sa.Column('transaction_trial_days_count', sa.Integer(), nullable=False),
    sa.Column('transaction_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribertransaction_customer_id'), 'subscribertransaction', ['customer_id'], unique=False)
    op.create_table('subsubscribertransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('financial_transaction_amount', sa.Float(), nullable=False),
    sa.Column('financial_transaction_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('financial_discount_amount', sa.Float(), nullable=False),
    sa.Column('csr_user_id', sa.Integer(), nullable=True),
    sa.Column('csr_user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('csr_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_livemode', sa.Boolean(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'promotion', 'credit', 'usage', 'cancelled', 'note', 'balance_forward', name='subscribertransactiontype'), nullable=False),
    sa.Column('transaction_units', sa.Enum('days', 'months', 'years', name='subscribertransactionunits'), nullable=False),
    sa.Column('transaction_month_count', sa.Integer(), nullable=False),
    sa.Column('transaction_day_count', sa.Integer(), nullable=False),
    sa.Column('transaction_trial_days_count', sa.Integer(), nullable=False),
    sa.Column('transaction_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_customer_id', sa.Integer(), nullable=True),
    sa.Column('primary_customer_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsubscribertransaction_primary_customer_id'), 'subsubscribertransaction', ['primary_customer_id'], unique=False)
    op.create_index(op.f('ix_subsubscribertransaction_sub_customer_id'), 'subsubscribertransaction', ['sub_customer_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_admin', sa.Boolean(), nullable=False),
    sa.Column('power_user_mode', sa.Integer(), nullable=False),
    sa.Column('system_user_mode', sa.Integer(), nullable=False),
    sa.Column('client_settings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_disabled', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('userpasswordreset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_used_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpasswordreset_token'), 'userpasswordreset', ['token'], unique=True)
    op.create_table('usersessionlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('computer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remote_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpasswords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userpasswords')
    op.drop_table('usersessionlog')
    op.drop_index(op.f('ix_userpasswordreset_token'), table_name='userpasswordreset')
    op.drop_table('userpasswordreset')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subsubscribertransaction_sub_customer_id'), table_name='subsubscribertransaction')
    op.drop_index(op.f('ix_subsubscribertransaction_primary_customer_id'), table_name='subsubscribertransaction')
    op.drop_table('subsubscribertransaction')
    op.drop_index(op.f('ix_subscribertransaction_customer_id'), table_name='subscribertransaction')
    op.drop_table('subscribertransaction')
    op.drop_index(op.f('ix_subcustomer_sub_customer_email'), table_name='subcustomer')
    op.drop_index(op.f('ix_subcustomer_sub_customer_account'), table_name='subcustomer')
    op.drop_index(op.f('ix_subcustomer_primary_customer_id'), table_name='subcustomer')
    op.drop_index(op.f('ix_subcustomer_application_tag'), table_name='subcustomer')
    op.drop_table('subcustomer')
    op.drop_index(op.f('ix_stripeevent_stripe_event_id'), table_name='stripeevent')
    op.drop_index(op.f('ix_stripeevent_stripe_customer_id'), table_name='stripeevent')
    op.drop_index(op.f('ix_stripeevent_primary_customer_id'), table_name='stripeevent')
    op.drop_table('stripeevent')
    op.drop_index(op.f('ix_emailactivitylog_remote_ip'), table_name='emailactivitylog')
    op.drop_index(op.f('ix_emailactivitylog_email_address'), table_name='emailactivitylog')
    op.drop_table('emailactivitylog')
    op.drop_index(op.f('ix_customerapplication_customer_stripe_hook'), table_name='customerapplication')
    op.drop_index(op.f('ix_customerapplication_customer_id'), table_name='customerapplication')
    op.drop_index(op.f('ix_customerapplication_application_tag'), table_name='customerapplication')
    op.drop_table('customerapplication')
    op.drop_index(op.f('ix_customer_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_customer_account'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('applicationlogevent')
    op.drop_index(op.f('ix_apiwebinvocationevent_unique_tracking_id'), table_name='apiwebinvocationevent')
    op.drop_index(op.f('ix_apiwebinvocationevent_customer_id'), table_name='apiwebinvocationevent')
    op.drop_index(op.f('ix_apiwebinvocationevent_authentication_key_id'), table_name='apiwebinvocationevent')
    op.drop_index(op.f('ix_apiwebinvocationevent_api_configuration_id'), table_name='apiwebinvocationevent')
    op.drop_table('apiwebinvocationevent')
    op.drop_index(op.f('ix_apiaccessconfiguration_customer_id'), table_name='apiaccessconfiguration')
    op.drop_index(op.f('ix_apiaccessconfiguration_authentication_key_id'), table_name='apiaccessconfiguration')
    op.drop_index(op.f('ix_apiaccessconfiguration_application_tag'), table_name='apiaccessconfiguration')
    op.drop_table('apiaccessconfiguration')
    # ### end Alembic commands ###
