"""updates subsubscriber trans with customer email and app info

Revision ID: 29c2d9db934d
Revises: 214c4d6a4a26
Create Date: 2026-07-13 00:20:24.440529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '29c2d9db934d'
down_revision: Union[str, None] = '214c4d6a4a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsubscribertransaction', sa.Column('sub_customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subsubscribertransaction', sa.Column('application_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_subsubscribertransaction_application_tag'), 'subsubscribertransaction', ['application_tag'], unique=False)
    op.create_index(op.f('ix_subsubscribertransaction_sub_customer_email'), 'subsubscribertransaction', ['sub_customer_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subsubscribertransaction_sub_customer_email'), table_name='subsubscribertransaction')
    op.drop_index(op.f('ix_subsubscribertransaction_application_tag'), table_name='subsubscribertransaction')
    op.drop_column('subsubscribertransaction', 'application_tag')
    op.drop_column('subsubscribertransaction', 'sub_customer_email')
    # ### end Alembic commands ###
