"""add application found and active in probe log

Revision ID: 3dff112a0c84
Revises: d480f908424c
Create Date: 2026-07-16 18:20:42.498307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dff112a0c84'
down_revision: Union[str, None] = 'd480f908424c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcustomerprobeevent', sa.Column('application_found', sa.Boolean(), nullable=True))
    op.add_column('subcustomerprobeevent', sa.Column('application_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcustomerprobeevent', 'application_active')
    op.drop_column('subcustomerprobeevent', 'application_found')
    # ### end Alembic commands ###
