"""misc updates and email data

Revision ID: 40828fe74b43
Revises: c4d5e6f7a8b9
Create Date: 2026-08-07 16:09:52.597583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '40828fe74b43'
down_revision: Union[str, None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customerproject_customer_deleted', table_name='customerproject')
    op.drop_index('ix_customerprojectalternatives_customer_project_deleted', table_name='customerprojectalternatives')
    op.drop_index('ix_customerprojectfactors_customer_project_deleted', table_name='customerprojectfactors')
    op.add_column('emailactivitylog', sa.Column('email_service', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_projectvoteobservation_customer_project_deleted', table_name='projectvoteobservation')
    op.drop_index('ix_projectvoteparticipant_customer_project_deleted', table_name='projectvoteparticipant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projectvoteparticipant_customer_project_deleted', 'projectvoteparticipant', ['customer_id', 'project_id', 'deleted_date'], unique=False)
    op.create_index('ix_projectvoteobservation_customer_project_deleted', 'projectvoteobservation', ['customer_id', 'project_id', 'deleted_date'], unique=False)
    op.drop_column('emailactivitylog', 'email_service')
    op.create_index('ix_customerprojectfactors_customer_project_deleted', 'customerprojectfactors', ['customer_id', 'project_id', 'deleted_date'], unique=False)
    op.create_index('ix_customerprojectalternatives_customer_project_deleted', 'customerprojectalternatives', ['customer_id', 'project_id', 'deleted_date'], unique=False)
    op.create_index('ix_customerproject_customer_deleted', 'customerproject', ['customer_id', 'deleted_date'], unique=False)
    # ### end Alembic commands ###
