"""subscriber transaction changes

Revision ID: 5e362281316b
Revises: 0a639f33bdf1
Create Date: 2026-07-15 16:29:32.060406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5e362281316b'
down_revision: Union[str, None] = '0a639f33bdf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribertransaction', sa.Column('financial_event_id', sa.Integer(), nullable=True))
    op.add_column('subscribertransaction', sa.Column('financial_event_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subscribertransaction', sa.Column('livemode_flag', sa.Boolean(), nullable=False))
    op.drop_column('subscribertransaction', 'stripe_event_id')
    op.drop_column('subscribertransaction', 'stripe_livemode')
    op.add_column('subsubscribertransaction', sa.Column('financial_event_id', sa.Integer(), nullable=True))
    op.add_column('subsubscribertransaction', sa.Column('financial_event_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subsubscribertransaction', sa.Column('livemode_flag', sa.Boolean(), nullable=False))
    op.drop_column('subsubscribertransaction', 'stripe_event_id')
    op.drop_column('subsubscribertransaction', 'stripe_livemode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsubscribertransaction', sa.Column('stripe_livemode', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subsubscribertransaction', sa.Column('stripe_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subsubscribertransaction', 'livemode_flag')
    op.drop_column('subsubscribertransaction', 'financial_event_source')
    op.drop_column('subsubscribertransaction', 'financial_event_id')
    op.add_column('subscribertransaction', sa.Column('stripe_livemode', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subscribertransaction', sa.Column('stripe_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subscribertransaction', 'livemode_flag')
    op.drop_column('subscribertransaction', 'financial_event_source')
    op.drop_column('subscribertransaction', 'financial_event_id')
    # ### end Alembic commands ###
