"""subscriber transaction fix field name

Revision ID: 91287d933771
Revises: 5e362281316b
Create Date: 2026-07-15 16:38:47.073936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '91287d933771'
down_revision: Union[str, None] = '5e362281316b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribertransaction', sa.Column('financial_event_row_id', sa.Integer(), nullable=True))
    op.drop_column('subscribertransaction', 'financial_event_id')
    op.add_column('subsubscribertransaction', sa.Column('financial_event_row_id', sa.Integer(), nullable=True))
    op.drop_column('subsubscribertransaction', 'financial_event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsubscribertransaction', sa.Column('financial_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subsubscribertransaction', 'financial_event_row_id')
    op.add_column('subscribertransaction', sa.Column('financial_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subscribertransaction', 'financial_event_row_id')
    # ### end Alembic commands ###
