"""add sub_customer_id in probe log

Revision ID: d480f908424c
Revises: e2f794ee16f1
Create Date: 2026-07-16 17:42:22.388467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd480f908424c'
down_revision: Union[str, None] = 'e2f794ee16f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcustomerprobeevent', sa.Column('sub_customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subcustomerprobeevent_sub_customer_id'), 'subcustomerprobeevent', ['sub_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcustomerprobeevent_sub_customer_id'), table_name='subcustomerprobeevent')
    op.drop_column('subcustomerprobeevent', 'sub_customer_id')
    # ### end Alembic commands ###
