"""subscriber transaction fix field name

Revision ID: e2f794ee16f1
Revises: 91287d933771
Create Date: 2026-07-15 16:53:13.658707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e2f794ee16f1'
down_revision: Union[str, None] = '91287d933771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribertransaction', sa.Column('financial_event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subsubscribertransaction', sa.Column('financial_event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsubscribertransaction', 'financial_event_type')
    op.drop_column('subscribertransaction', 'financial_event_type')
    # ### end Alembic commands ###
