"""watcher_llm_key_source_bytes

Revision ID: fb7d7d4374bd
Revises: 20ba6b8d0df6
Create Date: 2026-08-24 03:42:45.600854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7d7d4374bd'
down_revision: Union[str, None] = '20ba6b8d0df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watcher_llm_requests', sa.Column('key_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('watcher_llm_requests', sa.Column('prompt_bytes', sa.Integer(), nullable=True))
    op.add_column('watcher_llm_requests', sa.Column('response_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watcher_llm_requests', 'response_bytes')
    op.drop_column('watcher_llm_requests', 'prompt_bytes')
    op.drop_column('watcher_llm_requests', 'key_source')
    # ### end Alembic commands ###
